apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llmops

bases:
  - ../../base

patches:
  - path: patch-frontend-config.yaml
  - path: patch-resources.yaml
  - path: patch-ingress.yaml

# Tag all images with a specific production version
images:
  - name: ghcr.io/ashwithpoojary98/llmops-eval-backend
    newTag: "1.0.0"
  - name: ghcr.io/ashwithpoojary98/llmops-eval-engine
    newTag: "1.0.0"
  - name: ghcr.io/ashwithpoojary98/llmops-eval-frontend
    newTag: "1.0.0"
