apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llmops

resources:
  - namespace.yaml
  - secrets.yaml
  - network-policy.yaml
  - postgres.yaml
  - backend.yaml
  - evaluation-engine.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: llmops-platform
