apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llmops

bases:
  - ../../base

# Dev: single replica, local images, debug on
patches:
  - path: patch-replicas.yaml
  - path: patch-images.yaml
  - path: patch-frontend-config.yaml
